# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

android.useAndroidX=true
android.enableJetifier=true

# React Native
FLIPPER_VERSION=0.182.0
reactNativeArchitectures=arm64-v8a
newArchEnabled=false
hermesEnabled=true

# Kotlin
kotlin.daemon.jvm.options=-Xmx2g -XX:MaxMetaspaceSize=512m
